### ISSUE TITLE
I can't build Lighterpack

### ISSUE THREAD

**Issue by ilsaul** [galenmaly/lighterpack#237]
Hi,
I can't build it. I have:
* Debian 12.6
* Docker version 27.0.3, build 7d4bcd8

I execute the command
> sudo docker build -t lightpack:0.0.1 -t lightpack:latest .

Error:
[+] Building 68.2s (7/8)                                                                                       docker:default
 => [internal] load build definition from Dockerfile                                                                     0.0s
 => => transferring dockerfile: 578B                                                                                     0.0s
 => WARN: MaintainerDeprecated: Maintainer instruction is deprecated in favor of using label (line 2)                    0.0s
 => [internal] load metadata for docker.io/library/ubuntu:16.04                                                          1.5s
 => [internal] load .dockerignore                                                                                        0.1s
 => => transferring context: 2B                                                                                          0.0s
 => [1/5] FROM docker.io/library/ubuntu:16.04@sha256:1f1a2d56de1d604801a9671f301190704c25d604a416f59e03c04f5c6ffee0d6    3.9s
 => => resolve docker.io/library/ubuntu:16.04@sha256:1f1a2d56de1d604801a9671f301190704c25d604a416f59e03c04f5c6ffee0d6    0.0s
 => => sha256:a3785f78ab8547ae2710c89e627783cfa7ee7824d3468cae6835c9f4eae23ff7 1.15kB / 1.15kB                           0.0s
 => => sha256:b6f50765242581c887ff1acc2511fa2d885c52d8fb3ac8c4bba131fd86567f2e 3.36kB / 3.36kB                           0.0s
 => => sha256:58690f9b18fca6469a14da4e212c96849469f9b1be6661d2342a4bf01774aa50 46.50MB / 46.50MB                         1.0s
 => => sha256:b51569e7c50720acf6860327847fe342a1afbe148d24c529fb81df105e3eed01 857B / 857B                               0.3s
 => => sha256:da8ef40b9ecabc2679fe2419957220c0272a965c5cf7e0269fa1aeeb8c56f2e1 528B / 528B                               0.4s
 => => sha256:1f1a2d56de1d604801a9671f301190704c25d604a416f59e03c04f5c6ffee0d6 1.42kB / 1.42kB                           0.0s
 => => sha256:fb15d46c38dcd1ea0b1990006c3366ecd10c79d374f341687eb2cb23a2c8672e 170B / 170B                               0.5s
 => => extracting sha256:58690f9b18fca6469a14da4e212c96849469f9b1be6661d2342a4bf01774aa50                                2.6s
 => => extracting sha256:b51569e7c50720acf6860327847fe342a1afbe148d24c529fb81df105e3eed01                                0.0s
 => => extracting sha256:da8ef40b9ecabc2679fe2419957220c0272a965c5cf7e0269fa1aeeb8c56f2e1                                0.0s
 => => extracting sha256:fb15d46c38dcd1ea0b1990006c3366ecd10c79d374f341687eb2cb23a2c8672e                                0.0s
 => [2/5] RUN apt-get update -y && DEBIAN_FRONTEND=noninteractive apt-get install -qy   git   mongodb   nodejs   npm    56.2s
 => [3/5] RUN git clone https://github.com/galenmaly/lighterpack.git /var/www/lighterpack                                1.5s 
 => ERROR [4/5] RUN cd /var/www/lighterpack && npm install                                                               4.9s 
------                                                                                                                        
 > [4/5] RUN cd /var/www/lighterpack && npm install:                                                                          
1.195 WARN engine file-loader@6.2.0: wanted: {"node":">= 10.13.0"} (current: {"node":"4.2.6","npm":"3.5.2"})                  
1.256 WARN engine winston@3.13.1: wanted: {"node":">= 12.0.0"} (current: {"node":"4.2.6","npm":"3.5.2"})                      
1.277 npm WARN deprecated @babel/polyfill@7.2.5: 🚨 This package has been deprecated in favor of separate inclusion of a polyfill and regenerator-runtime (when needed). See the @babel/polyfill docs (https://babeljs.io/docs/en/babel-polyfill) for more information.
1.288 WARN engine request@2.88.2: wanted: {"node":">= 6"} (current: {"node":"4.2.6","npm":"3.5.2"})
1.294 WARN engine babel-loader@8.2.2: wanted: {"node":">= 8.9"} (current: {"node":"4.2.6","npm":"3.5.2"})
1.342 npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
1.385 WARN engine mini-css-extract-plugin@1.3.3: wanted: {"node":">= 10.13.0"} (current: {"node":"4.2.6","npm":"3.5.2"})
1.457 WARN engine css-loader@3.5.3: wanted: {"node":">= 8.9.0"} (current: {"node":"4.2.6","npm":"3.5.2"})
1.577 WARN engine sass-loader@10.1.0: wanted: {"node":">= 10.13.0"} (current: {"node":"4.2.6","npm":"3.5.2"})
1.597 WARN engine sass@1.32.0: wanted: {"node":">=8.9.0"} (current: {"node":"4.2.6","npm":"3.5.2"})
1.632 WARN engine @babel/core@7.12.10: wanted: {"node":">=6.9.0"} (current: {"node":"4.2.6","npm":"3.5.2"})
1.900 WARN engine mailgun-js@0.22.0: wanted: {"node":">=6.0.0"} (current: {"node":"4.2.6","npm":"3.5.2"})
1.964 npm WARN deprecated mailgun-js@0.22.0: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
2.205 npm WARN deprecated formidable@1.2.6: Please upgrade to latest, formidable@v2 or formidable@v3! Check these notes: https://bit.ly/2ZEqIau
2.602 npm WARN deprecated vue@2.6.12: Vue 2 has reached EOL and is no longer actively maintained. See https://v2.vuejs.org/eol/ for more details.
2.893 WARN engine webpack@5.11.1: wanted: {"node":">=10.13.0"} (current: {"node":"4.2.6","npm":"3.5.2"})
4.486 WARN engine gensync@1.0.0-beta.2: wanted: {"node":">=6.9.0"} (current: {"node":"4.2.6","npm":"3.5.2"})
4.536 WARN engine json5@2.2.3: wanted: {"node":">=6"} (current: {"node":"4.2.6","npm":"3.5.2"})
4.538 WARN engine debug@4.3.5: wanted: {"node":">=6.0"} (current: {"node":"4.2.6","npm":"3.5.2"})
4.558 npm ERR! Linux 6.1.0-22-amd64
4.558 npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
4.558 npm ERR! node v4.2.6
4.558 npm ERR! npm  v3.5.2
4.558 npm ERR! code EMISSINGARG
4.563 
4.563 npm ERR! typeerror Error: Missing required argument #1
4.563 npm ERR! typeerror     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
4.563 npm ERR! typeerror     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
4.563 npm ERR! typeerror     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
4.563 npm ERR! typeerror     at /usr/share/npm/lib/install/deps.js:457:7
4.563 npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
4.563 npm ERR! typeerror     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
4.563 npm ERR! typeerror     at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)
4.563 npm ERR! typeerror     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)
4.563 npm ERR! typeerror     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20)
4.563 npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
4.563 npm ERR! typeerror This is an error with npm itself. Please report this error at:
4.563 npm ERR! typeerror     <http://github.com/npm/npm/issues>
4.605 npm ERR! Linux 6.1.0-22-amd64
4.606 npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
4.606 npm ERR! node v4.2.6
4.606 npm ERR! npm  v3.5.2
4.606 npm ERR! code EMISSINGARG
4.606 
4.606 npm ERR! typeerror Error: Missing required argument #1
4.606 npm ERR! typeerror     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
4.606 npm ERR! typeerror     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
4.606 npm ERR! typeerror     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
4.606 npm ERR! typeerror     at /usr/share/npm/lib/install/deps.js:457:7
4.606 npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
4.606 npm ERR! typeerror     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
4.606 npm ERR! typeerror     at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)
4.606 npm ERR! typeerror     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)
4.606 npm ERR! typeerror     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20)
4.606 npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
4.607 npm ERR! typeerror This is an error with npm itself. Please report this error at:
4.607 npm ERR! typeerror     <http://github.com/npm/npm/issues>
4.615 npm ERR! Linux 6.1.0-22-amd64
4.616 npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
4.616 npm ERR! node v4.2.6
4.616 npm ERR! npm  v3.5.2
4.616 npm ERR! code EMISSINGARG
4.616 
4.616 npm ERR! typeerror Error: Missing required argument #1
4.616 npm ERR! typeerror     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
4.616 npm ERR! typeerror     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
4.616 npm ERR! typeerror     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
4.616 npm ERR! typeerror     at /usr/share/npm/lib/install/deps.js:457:7
4.616 npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
4.616 npm ERR! typeerror     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
4.616 npm ERR! typeerror     at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)
4.617 npm ERR! typeerror     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)
4.618 npm ERR! typeerror     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20)
4.618 npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
4.618 npm ERR! typeerror This is an error with npm itself. Please report this error at:
4.618 npm ERR! typeerror     <http://github.com/npm/npm/issues>
4.645 npm ERR! Linux 6.1.0-22-amd64
4.645 npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
4.645 npm ERR! node v4.2.6
4.645 npm ERR! npm  v3.5.2
4.645 npm ERR! code EMISSINGARG
4.645 
4.645 npm ERR! typeerror Error: Missing required argument #1
4.645 npm ERR! typeerror     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
4.645 npm ERR! typeerror     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
4.646 npm ERR! typeerror     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
4.646 npm ERR! typeerror     at /usr/share/npm/lib/install/deps.js:457:7
4.646 npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
4.646 npm ERR! typeerror     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
4.646 npm ERR! typeerror     at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)
4.647 npm ERR! typeerror     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)
4.647 npm ERR! typeerror     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20)
4.647 npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
4.647 npm ERR! typeerror This is an error with npm itself. Please report this error at:
4.647 npm ERR! typeerror     <http://github.com/npm/npm/issues>
4.659 npm ERR! Linux 6.1.0-22-amd64
4.659 npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
4.659 npm ERR! node v4.2.6
4.659 npm ERR! npm  v3.5.2
4.660 npm ERR! code EMISSINGARG
4.660 
4.660 npm ERR! typeerror Error: Missing required argument #1
4.660 npm ERR! typeerror     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
4.660 npm ERR! typeerror     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
4.660 npm ERR! typeerror     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
4.660 npm ERR! typeerror     at /usr/share/npm/lib/install/deps.js:457:7
4.660 npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
4.660 npm ERR! typeerror     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
4.660 npm ERR! typeerror     at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)
4.660 npm ERR! typeerror     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)
4.660 npm ERR! typeerror     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20)
4.660 npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
4.660 npm ERR! typeerror This is an error with npm itself. Please report this error at:
4.660 npm ERR! typeerror     <http://github.com/npm/npm/issues>
4.674 npm ERR! Linux 6.1.0-22-amd64
4.674 npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
4.674 npm ERR! node v4.2.6
4.674 npm ERR! npm  v3.5.2
4.674 npm ERR! code EMISSINGARG
4.674 
4.674 npm ERR! typeerror Error: Missing required argument #1
4.674 npm ERR! typeerror     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
4.675 npm ERR! typeerror     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
4.675 npm ERR! typeerror     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
4.675 npm ERR! typeerror     at /usr/share/npm/lib/install/deps.js:457:7
4.675 npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
4.675 npm ERR! typeerror     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
4.675 npm ERR! typeerror     at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)
4.675 npm ERR! typeerror     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)
4.675 npm ERR! typeerror     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20)
4.675 npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
4.675 npm ERR! typeerror This is an error with npm itself. Please report this error at:
4.676 npm ERR! typeerror     <http://github.com/npm/npm/issues>
4.681 npm ERR! Linux 6.1.0-22-amd64
4.682 npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
4.682 npm ERR! node v4.2.6
4.682 npm ERR! npm  v3.5.2
4.682 npm ERR! code EMISSINGARG
4.683 
4.683 npm ERR! typeerror Error: Missing required argument #1
4.683 npm ERR! typeerror     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
4.683 npm ERR! typeerror     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
4.683 npm ERR! typeerror     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
4.683 npm ERR! typeerror     at /usr/share/npm/lib/install/deps.js:457:7
4.683 npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
4.683 npm ERR! typeerror     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
4.683 npm ERR! typeerror     at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)
4.683 npm ERR! typeerror     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)
4.683 npm ERR! typeerror     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20)
4.683 npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
4.683 npm ERR! typeerror This is an error with npm itself. Please report this error at:
4.683 npm ERR! typeerror     <http://github.com/npm/npm/issues>
4.723 npm ERR! Linux 6.1.0-22-amd64
4.723 npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
4.724 npm ERR! node v4.2.6
4.724 npm ERR! npm  v3.5.2
4.724 npm ERR! code EMISSINGARG
4.724 
4.724 npm ERR! typeerror Error: Missing required argument #1
4.724 npm ERR! typeerror     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
4.724 npm ERR! typeerror     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
4.724 npm ERR! typeerror     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
4.724 npm ERR! typeerror     at /usr/share/npm/lib/install/deps.js:457:7
4.724 npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
4.724 npm ERR! typeerror     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
4.724 npm ERR! typeerror     at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)
4.724 npm ERR! typeerror     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)
4.724 npm ERR! typeerror     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20)
4.724 npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
4.724 npm ERR! typeerror This is an error with npm itself. Please report this error at:
4.724 npm ERR! typeerror     <http://github.com/npm/npm/issues>
4.820 
4.820 npm ERR! Please include the following file with any support request:
4.820 npm ERR!     /var/www/lighterpack/npm-debug.log
------

 2 warnings found (use --debug to expand):
 - MaintainerDeprecated: Maintainer instruction is deprecated in favor of using label (line 2)
 - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 3)
Dockerfile:17
--------------------
  15 |     
  16 |     # Move to the directory so we install the libraries in correct folder
  17 | >>> RUN cd /var/www/lighterpack && npm install
  18 |     
  19 |     # Web
--------------------
ERROR: failed to solve: process "/bin/sh -c cd /var/www/lighterpack && npm install" did not complete successfully: exit code: 1

**Comment by oliver-ruehl** [comment]
----------- I am not a programmer, this is from an AI (Mistral) that i use to fix some things -----
Hope it helps a little ;)

<h3><strong>Fix for Docker Build Error (Debian + Node.js 4.2.6 → npm EMISSINGARG)</strong></h3>
<p><strong>Problem:</strong>
Your build fails because:</p>
<ul>
<li><strong>Node.js 4.2.6</strong> (too old for modern packages like <code>webpack 5</code>).</li>
<li><strong>npm 3.5.2</strong> (buggy, throws <code>EMISSINGARG</code>).</li>
<li><strong>Debian’s default repos</strong> provide ancient Node.js versions.</li>
</ul>
<hr>
<h3><strong>Solution: Use Debian 12 + Node.js 18 (via NodeSource)</strong></h3>
<p>Update your <code>Dockerfile</code> to use <strong>Debian 12 (Bookworm)</strong> and install Node.js 18 via NodeSource:</p>
<div class="copy-code-wrap"><div class="copy-code-button-wrapper"></div><pre><code class="hljs language-dockerfile"># Use Debian 12 (Bookworm) as base
FROM debian:12

# Install dependencies and Node.js 18.x
RUN apt-get update &amp;&amp; apt-get install -y --no-install-recommends \
    git \
    curl \
    ca-certificates \
    gnupg2 \
    &amp;&amp; curl -fsSL https://deb.nodesource.com/setup_18.x | bash - \
    &amp;&amp; apt-get install -y nodejs \
    &amp;&amp; npm install -g npm@latest  # Update npm to latest

# Clone and install the app
WORKDIR /var/www/lighterpack
COPY . .
RUN npm install
</code></pre></div><hr>
<h3><strong>Alternative: Use Official <code>node:18</code> Image (Recommended)</strong></h3>
<p>If you don’t <em>need</em> Debian specifically, the simplest fix is to switch to the official Node.js image (Debian-based):</p>
<div class="copy-code-wrap"><div class="copy-code-button-wrapper"></div><pre><code class="hljs language-dockerfile">FROM node:18-bookworm  # Debian 12 + Node.js 18

WORKDIR /var/www/lighterpack
COPY . .
RUN npm install
</code></pre></div><hr>
<h3><strong>Why This Works</strong></h3>

Issue | Fix | Result
-- | -- | --
Node.js 4.2.6 → too old | Node.js 18.x (LTS) | Compatible with modern packages
npm 3.5.2 → buggy | npm 9.x | No EMISSINGARG errors
Debian old repos | NodeSource or node:18 | Gets latest Node.js
